### ISSUE TITLE
actions are not handled

### ISSUE THREAD

**Issue by islam-hamza** [erikw/dotfiles#1]
Hey, I'm trying to give your dots a try I'm getting this error

Action asdf not handled
Action crontab not handled
Action firefox not handled
Action ghq not handled

and 

Command [~/bin/macos_config.sh] failed

any suggestions what might be causing this ?
I looked at the config files they seem fine

**Comment by erikw** [comment]
Hey, 

scripts like `~/bin/macos_config.sh` are highly personal to me and I don't expect that anyone else would want to run them just like that. They can be a good inspiration, but it's very unlikely that you want all the things that are in scripts like that one.

I would look directly at the instructions at https://github.com/anishathalye/dotbot and use that for your own dot files repo. Instead peek at mine for inspiration, but it's not really made for that someone else uses it straight off :)

**Comment by erikw** [comment]
The issue might be that the git submodules are not cloned

```bash
git submodule update --init --recursive
```

**Comment by erikw** [comment]
which did not happen due to a mistake I recently made. Thanks for pointing it out!


https://github.com/erikw/dotfiles/commit/43d7402b02d0e8a3ba5fdd7206b449ea9051ef84

**Comment by islam-hamza** [comment]
Thank you for taking some time to look into this,
I tested things out and it's the path , the asdf and other plugins doesn't see the updated path
so with the current setup you have to run the install twice so the plugins see the updated path
